#purpose of this file is to store the application URL
#maintain the application credentials
#Maintain the browser configuration
#Which browser to be used

Browser=Chrome

URL=http://www.example.com

UserName=abc
Password=abcd

KillExistingBrowsers=True
BrowserClose=False

Incognito= False

Headless=False